---
path:
  output: assets
  css: css
  js: js

# set to true to upload to s3 after building the aessts
# you might want to map your `asset_host` to s3 with cname
s3: false

css:
  # css group name
  common:
    site:
      - common/layout
      - common/content
  error:
    site:
      - error/base
  home:
    site:
      - home/index
  admin-home:
    site:
      - admin/base
      - admin/home/index
  news-index:
    site:
      - news/index
  admin-news-index:
    site:
      - news/index
      - admin/base
      - admin/news/index
  news-show:
    site:
      - news/show
  admin-news-show:
    site:
      - news/show
      - admin/base
      - admin/news/show
  admin-news-new:
    site:
      - admin/base
      - admin/news/new
  artists-index:
    site:
      - artists/index
  admin-artists-index:
    site:
      - artists/index
      - admin/base
      - admin/artists/index
  artists-show:
    site:
      - artists/show
  admin-artists-show:
    site:
      - artists/show
      - admin/base
      - admin/artists/show
  admin-artists-new:
    site:
      - admin/base
      - admin/artists/new
  releases-index:
    site:
      - releases/index
  admin-releases-index:
    site:
      - releases/index
      - admin/base
      - admin/releases/index
  admin-releases-new:
    site:
      - admin/base
      - admin/releases/new
  releases-show:
    site:
      - releases/show
  admin-releases-show:
    site:
      - releases/show
      - admin/base
      - admin/releases/show
  videos-index:
    site:
      - videos/index
  admin-videos-new:
    site:
      - admin/base
      - admin/videos/new
  admin-videos-index:
    site:
      - videos/index
      - admin/base
      - admin/videos/index
  live-index:
    site:
      - live/index
  admin-live-index:
    site:
      - live/index
      - admin/base
      - admin/live/index
  admin-live-new:
    site:
      - admin/base
      - admin/live/new
  contact-index:
    site:
      - contact/index
  sessions:
    site:
      - sessions/new

js:
  # js group name
  common:
    cdn:
      # - https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
    site:
      - common/ga
