---
path:
  output: assets
  css: css
  js: js

# set to true to upload to s3 after building the aessts
# you might want to map your `asset_host` to s3 with cname
s3: false

css:
  # css group name
  common:
    site:
      - common/reset
      - common/util
      - common/base
      - common/header
      - common/nav
      - common/flash
      - common/footer
  scaffold:
    site:
      - scaffold

js:
  # js group name
  common:
    cdn:
      - https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
    site:
      - common/ga
