---
path:
  output: assets
  css: css
  js: js

# set to true to upload to s3 after building the aessts
# you might want to map your `asset_host` to s3 with cname
s3: false

css:
  # css group name
  common:
    site:
      - common/layout
  home:
    site:
      - home/index
  news-index:
    site:
      - news/index
  news-show:
    site:
      - news/show
  releases-index:
    site:
      - releases/index
  releases-show:
    site:
      - releases/show

js:
  # js group name
  common:
    cdn:
      # - https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js
    site:
      - common/ga
